### PR TITLE
support custom CA bundle for the api-server, and options for MetalLB

### PR DESCRIPTION
**Pull request by mluds**
My corporate network uses TLS inspection, and so a self-signed CA cert needs to be added to the bundle for Internet access.

### CODE REVIEW

**Comment by cure** [comment]
Hi @mluds thanks for your contribution! 

Could I ask you to add a copyright header to the `charts/arvados/templates/custom-ca-bundle-configmap.yaml` file, please? That wasn't mentioned in the `Contributing` section of the README yet, sorry about that. I've added a link there that points to how to do it. If you could rebase the commit https://github.com/arvados/arvados-k8s/pull/1/commits/548ee3f209b95bbd9d25f603ce8793bb18419f6b with that change, then I will be able to merge this PR (we have a git commit hook that requires the headers). Feel free to add yourself to the AUTHORS file, as well!

**Comment by mluds** [comment]
Should be all set now, thank you

**Comment by cure** [comment]
Hi @mluds I am happy to merge; it looks like you missed a DCO signoff on https://github.com/arvados/arvados-k8s/pull/1/commits/c984df283aef76c6649772e425b6e64c9d5576cd though, could you fix that? Sorry for the hassle.

**Comment by mluds** [comment]
No problem, should be fixed now

**Comment by cure** [comment]
Thank you @mluds, merged now.

**Pull request merged**
